### ISSUE TITLE
[Feature] Regular.md needs to be updated

### ISSUE THREAD

**Issue by shubhsharma19** [Pradumnasaraf/open-source-with-pradumna#251] opened 2023-05-07 07:20 UTC
The`regular.md` is not updated after December 2022. Update the table with the post image and links to the post.

<img width="1243" alt="Screenshot 2023-05-10 at 12 50 38 PM" src="https://github.com/Pradumnasaraf/open-source-with-pradumna/assets/51878265/1e1d0d4f-ad3e-429d-a568-e96b668df842">

**Page link**: https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/Regular.md

**Comment by Pradumnasaraf** [comment] 2023-05-08 17:11
Hey, Shub

Thanks for opening the issue. The Tweets are sorted correctly (latest tweets at the top), the issue is it's not updated after 22nd Dec 2022 :)

So the issue is to update the post after **22nd Dec 2022**

**Comment by shubhsharma19** [comment] 2023-05-08 17:12
Oh ok alright! got it

**Comment by Pradumnasaraf** [comment] 2023-05-08 17:56
> Oh ok alright! got it , I will close the issue now

No need to close. Just update the title and info.

**Comment by SahilSinghTomar** [comment] 2023-06-23 18:53
can u give more details on the issue.

**Comment by KshitizRana** [comment] 2023-06-29 12:42
#255Add New posts in regular.md
merge pull request.

**Comment by Pradumnasaraf** [comment] 2023-06-30 05:22
> can u give more details on the issue.

Hey, you take a look at my Twitter timeline and search for posts related to open source, Git, or GitHub after December 22, 2022. Use https://poet.so/ to create an image and link, similar to what has already been done on https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/Regular.md.

**Comment by Pradumnasaraf** [comment] 2023-06-30 05:24
> #255Add New posts in regular.md merge pull request.

Follow the guidelines [CONTRIBUTING.md](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/CONTRIBUTING.md). Issue is not assigned to you.

**Comment by KshitizRana** [comment] 2023-06-30 05:58
May work on this Issue?
Please assign it to me

**Comment by Pradumnasaraf** [comment] 2023-06-30 06:01
> May work on this Issue? 
Please assign it to me

I will wait for Sahil's reply 1st, as they commented 1st.

**Comment by SahilSinghTomar** [comment] 2023-06-30 17:57
hii @Pradumnasaraf i would like to work on this issue.

but there are so many post of u on twitter after dec 2022 about open source

it will take some time to complete

**Comment by SahilSinghTomar** [comment] 2023-06-30 17:59
are there any tools to filter twitter post on the bases of date or tags

**Comment by shubhsharma19** [comment] 2023-07-02 06:30
> hii @Pradumnasaraf i would like to work on this issue.
> 
> but there are so many post of u on twitter after dec 2022 about open source
> 
> it will take some time to complete

You can use twitter's advanced search feature and then look up to the posts after december 2022, you can also start from january 2023 and then add those.

**Comment by SahilSinghTomar** [comment] 2023-07-02 10:44
yup thanks <3

**Comment by Pradumnasaraf** [comment] 2023-07-02 12:23
Thanks for answering @shubhsharma19. I have assigned the issue @SahilSinghTomar.

**Comment by SahilSinghTomar** [comment] 2023-07-02 14:25
Thank you we start working on this asap

**Comment by Pradumnasaraf** [comment] 2023-07-05 19:43
closes #259

**Closed by Pradumnasaraf** 2023-07-05 19:43 UTC
Labels: documentation, good first issue, EddieHub:good-first-issue, feature
